### ISSUE TITLE
Chapter 8 - Second shiny page not found

### ISSUE THREAD

**Issue by BartlettJE** [PsyTeachR/quant-fun-v2#11]
On line 387, there should be a link to the Shiny app for playing around with a normal disitribution: 
[access it here](http://shiny.psy.gla.ac.uk/jackt/ShinyPsyTeachR/ug1/normal-distributions/)

However, it comes up as page not found:
Page not found
Sorry, but the page you requested doesn't exist.

**Comment by philmcaleer** [comment]
Hey James, Can you check it now as I can see it.

**Comment by philmcaleer** [comment]
ignore me - I see what you mean. Will see if I can fix this
